function selectOptions(values) {
  return values.map((value) =>
    typeof value === "string" ? { label: value, value } : value,
  );
}

const generatorTools = [
  {
    id: "passwordGenerator",
    slug: "gerador-de-senha",
    family: "generator",
    category: "geradores",
    badge: "PWD",
    name: "Gerador de Senha",
    description: "Monta senhas fortes com combinacoes configuraveis.",
    accent: "from-orange-500 to-rose-500",
    inputs: [
      { name: "length", label: "Tamanho", type: "number", placeholder: "16", required: true },
      { name: "uppercase", label: "Maiusculas", type: "checkbox" },
      { name: "numbers", label: "Numeros", type: "checkbox" },
      { name: "symbols", label: "Simbolos", type: "checkbox" },
    ],
  },
  {
    id: "uuidGenerator",
    slug: "gerador-de-uuid",
    family: "generator",
    category: "geradores",
    badge: "UUID",
    name: "Gerador de UUID",
    description: "Cria UUIDs v4 em lote para testes e integracoes.",
    accent: "from-cyan-500 to-sky-600",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true }],
  },
  {
    id: "loremGenerator",
    slug: "gerador-de-lorem",
    family: "generator",
    category: "geradores",
    badge: "LOREM",
    name: "Gerador de Lorem Ipsum",
    description: "Produz paragrafos rapidos para wireframes e prototipos.",
    accent: "from-violet-400 to-fuchsia-500",
    inputs: [{ name: "paragraphs", label: "Paragrafos", type: "number", placeholder: "3", required: true }],
  },
  {
    id: "documentGenerator",
    slug: "gerador-cpf-cnpj",
    family: "generator",
    category: "geradores",
    badge: "DOC",
    name: "Gerador de CPF e CNPJ",
    description: "Gera documentos validos para ambiente de desenvolvimento.",
    accent: "from-emerald-500 to-cyan-500",
    inputs: [
      {
        name: "documentType",
        label: "Tipo de documento",
        type: "select",
        required: true,
        options: selectOptions([
          { label: "CPF", value: "cpf" },
          { label: "CNPJ", value: "cnpj" },
        ]),
      },
    ],
  },
  {
    id: "nanoIdGenerator",
    slug: "gerador-de-nanoid",
    family: "generator",
    category: "geradores",
    badge: "NID",
    name: "Gerador de Nano ID",
    description: "Cria ids curtos e amigaveis para frontend e APIs.",
    accent: "from-sky-500 to-indigo-600",
    inputs: [
      { name: "length", label: "Tamanho", type: "number", placeholder: "12", required: true },
      { name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true },
    ],
  },
  {
    id: "apiKeyGenerator",
    slug: "gerador-de-api-key",
    family: "generator",
    category: "geradores",
    badge: "KEY",
    name: "Gerador de API Key",
    description: "Monta chaves com prefixo opcional para integracoes.",
    accent: "from-cyan-500 to-blue-600",
    inputs: [
      { name: "prefix", label: "Prefixo", type: "text", placeholder: "sk_live", required: false },
      { name: "length", label: "Tamanho", type: "number", placeholder: "32", required: true },
      { name: "count", label: "Quantidade", type: "number", placeholder: "3", required: true },
    ],
  },
  {
    id: "couponCodeGenerator",
    slug: "gerador-de-cupom",
    family: "generator",
    category: "geradores",
    badge: "SALE",
    name: "Gerador de Cupom",
    description: "Cria cupons em lote com prefixo e blocos padronizados.",
    accent: "from-orange-500 to-amber-500",
    inputs: [
      { name: "prefix", label: "Prefixo", type: "text", placeholder: "PROMO", required: false },
      { name: "length", label: "Tamanho", type: "number", placeholder: "10", required: true },
      { name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true },
    ],
  },
  {
    id: "hexColorGenerator",
    slug: "gerador-de-cores-hex",
    family: "generator",
    category: "geradores",
    badge: "HEX",
    name: "Gerador de Cores HEX",
    description: "Gera paletas rapidas com cores aleatorias.",
    accent: "from-fuchsia-500 to-violet-600",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true }],
  },
  {
    id: "gradientGenerator",
    slug: "gerador-de-gradiente",
    family: "generator",
    category: "geradores",
    badge: "CSS",
    name: "Gerador de Gradiente CSS",
    description: "Cria gradients prontos para uso em CSS.",
    accent: "from-pink-500 to-orange-500",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "3", required: true }],
  },
  {
    id: "fakeUserGenerator",
    slug: "gerador-de-usuario-fake",
    family: "generator",
    category: "geradores",
    badge: "USER",
    name: "Gerador de Usuario Fake",
    description: "Monta perfis falsos para prototipos e seeds.",
    accent: "from-emerald-500 to-cyan-600",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true }],
  },
  {
    id: "fakeAddressGenerator",
    slug: "gerador-de-endereco-fake",
    family: "generator",
    category: "geradores",
    badge: "ADDR",
    name: "Gerador de Endereco Fake",
    description: "Cria enderecos brasileiros ficticios para testes.",
    accent: "from-cyan-500 to-teal-600",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true }],
  },
  {
    id: "usernameGenerator",
    slug: "gerador-de-username",
    family: "generator",
    category: "geradores",
    badge: "UID",
    name: "Gerador de Username",
    description: "Gera usernames amigaveis com base opcional.",
    accent: "from-blue-500 to-indigo-500",
    inputs: [
      { name: "base", label: "Base", type: "text", placeholder: "max", required: false },
      { name: "count", label: "Quantidade", type: "number", placeholder: "8", required: true },
    ],
  },
  {
    id: "ipv4Generator",
    slug: "gerador-de-ipv4",
    family: "generator",
    category: "geradores",
    badge: "IPv4",
    name: "Gerador de IPv4",
    description: "Cria enderecos IPv4 aleatorios para mock e documentacao.",
    accent: "from-slate-600 to-blue-700",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true }],
  },
  {
    id: "macAddressGenerator",
    slug: "gerador-de-mac-address",
    family: "generator",
    category: "geradores",
    badge: "MAC",
    name: "Gerador de MAC Address",
    description: "Produz enderecos MAC formatados em lote.",
    accent: "from-slate-700 to-cyan-700",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true }],
  },
  {
    id: "timestampGenerator",
    slug: "gerador-de-timestamps",
    family: "generator",
    category: "geradores",
    badge: "TIME",
    name: "Gerador de Timestamps",
    description: "Gera snapshots de data com unix, ISO e local string.",
    accent: "from-amber-400 to-orange-500",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "3", required: true }],
  },
  {
    id: "creditCardGenerator",
    slug: "gerador-de-cartao",
    family: "generator",
    category: "geradores",
    badge: "CARD",
    name: "Gerador de Cartao",
    description: "Cria numeros de cartao validos por Luhn para sandbox.",
    accent: "from-violet-500 to-fuchsia-500",
    inputs: [
      { name: "brand", label: "Bandeira", type: "select", required: true, options: selectOptions(["visa", "mastercard", "amex"]) },
      { name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true },
    ],
  },
  {
    id: "licensePlateGenerator",
    slug: "gerador-de-placa",
    family: "generator",
    category: "geradores",
    badge: "CAR",
    name: "Gerador de Placa",
    description: "Gera placas no formato antigo ou Mercosul.",
    accent: "from-cyan-500 to-lime-500",
    inputs: [
      {
        name: "mode",
        label: "Formato",
        type: "select",
        required: true,
        options: selectOptions([
          { label: "Mercosul", value: "mercosul" },
          { label: "Antigo", value: "old" },
        ]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true },
    ],
  },
  {
    id: "ean13Generator",
    slug: "gerador-de-ean13",
    family: "generator",
    category: "geradores",
    badge: "EAN",
    name: "Gerador de EAN-13",
    description: "Monta codigos EAN-13 com digito verificador valido.",
    accent: "from-orange-500 to-rose-500",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true }],
  },
  {
    id: "pixKeyGenerator",
    slug: "gerador-de-chave-pix",
    family: "generator",
    category: "geradores",
    badge: "PIX",
    name: "Gerador de Chave PIX",
    description: "Cria chaves de teste no formato EVP, email, telefone ou CPF.",
    accent: "from-emerald-500 to-lime-500",
    inputs: [
      {
        name: "keyType",
        label: "Tipo",
        type: "select",
        required: true,
        options: selectOptions([
          { label: "EVP", value: "evp" },
          { label: "Email", value: "email" },
          { label: "Telefone", value: "phone" },
          { label: "CPF", value: "cpf" },
        ]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true },
    ],
  },
  {
    id: "htmlTableGenerator",
    slug: "gerador-de-tabela-html",
    family: "generator",
    category: "geradores",
    badge: "TABLE",
    name: "Gerador de Tabela HTML",
    description: "Entrega uma tabela HTML basica com linhas e colunas configuradas.",
    accent: "from-blue-500 to-cyan-600",
    inputs: [
      { name: "rows", label: "Linhas", type: "number", placeholder: "4", required: true },
      { name: "columns", label: "Colunas", type: "number", placeholder: "3", required: true },
    ],
  },
  {
    id: "mockJsonGenerator",
    slug: "gerador-de-mock-json",
    family: "generator",
    category: "geradores",
    badge: "MOCK",
    name: "Gerador de Mock JSON",
    description: "Gera colecoes JSON simples para UI e API mocking.",
    accent: "from-indigo-500 to-blue-600",
    inputs: [{ name: "items", label: "Itens", type: "number", placeholder: "5", required: true }],
  },
  {
    id: "sqlSeedGenerator",
    slug: "gerador-de-sql-seed",
    family: "generator",
    category: "geradores",
    badge: "SQL",
    name: "Gerador de SQL Seed",
    description: "Cria inserts de exemplo para popular ambientes de teste.",
    accent: "from-slate-700 to-indigo-700",
    inputs: [
      { name: "tableName", label: "Tabela", type: "text", placeholder: "users", required: true },
      { name: "rows", label: "Linhas", type: "number", placeholder: "5", required: true },
    ],
  },
  {
    id: "userAgentGenerator",
    slug: "gerador-de-user-agent",
    family: "generator",
    category: "geradores",
    badge: "UA",
    name: "Gerador de User-Agent",
    description: "Produz strings de user-agent para navegador e dispositivo.",
    accent: "from-slate-600 to-teal-700",
    inputs: [
      { name: "browser", label: "Browser", type: "select", required: true, options: selectOptions(["chrome", "firefox", "safari"]) },
      { name: "device", label: "Dispositivo", type: "select", required: true, options: selectOptions(["desktop", "mobile"]) },
      { name: "count", label: "Quantidade", type: "number", placeholder: "3", required: true },
    ],
  },
  {
    id: "cssShadowGenerator",
    slug: "gerador-de-box-shadow",
    family: "generator",
    category: "geradores",
    badge: "SHDW",
    name: "Gerador de Box Shadow",
    description: "Cria sombras CSS variadas para componentes e cards.",
    accent: "from-slate-500 to-cyan-600",
    inputs: [{ name: "count", label: "Quantidade", type: "number", placeholder: "5", required: true }],
  },
  {
    id: "nicknameGenerator",
    slug: "gerador-de-nickname",
    family: "generator",
    category: "geradores",
    badge: "NICK",
    name: "Gerador de Nickname",
    description: "Monta nicks em estilos gamer, clean, cute ou dark.",
    accent: "from-indigo-500 to-fuchsia-500",
    inputs: [
      { name: "base", label: "Base", type: "text", placeholder: "max", required: false },
      {
        name: "style",
        label: "Estilo",
        type: "select",
        required: true,
        options: selectOptions(["gamer", "clean", "cute", "dark"]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "12", required: true },
    ],
  },
  {
    id: "emoticonGenerator",
    slug: "gerador-de-emoticons",
    family: "generator",
    category: "geradores",
    badge: "FACE",
    name: "Gerador de Emoticons",
    description: "Entrega carinhas em estilo classico, kaomoji ou misto.",
    accent: "from-amber-400 to-pink-500",
    inputs: [
      {
        name: "mood",
        label: "Humor",
        type: "select",
        required: true,
        options: selectOptions(["happy", "love", "shrug", "sad", "rage"]),
      },
      {
        name: "style",
        label: "Estilo",
        type: "select",
        required: true,
        options: selectOptions(["mixed", "classic", "kaomoji"]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true },
    ],
  },
  {
    id: "emojiComboGenerator",
    slug: "gerador-de-combos-emoji",
    family: "generator",
    category: "geradores",
    badge: "EMJ",
    name: "Gerador de Combos Emoji",
    description: "Cria combinacoes curtas de emojis por tema.",
    accent: "from-yellow-400 to-orange-500",
    inputs: [
      {
        name: "theme",
        label: "Tema",
        type: "select",
        required: true,
        options: selectOptions(["celebration", "love", "gamer", "study", "food", "travel"]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "8", required: true },
    ],
  },
  {
    id: "bioGenerator",
    slug: "gerador-de-bio",
    family: "generator",
    category: "geradores",
    badge: "BIO",
    name: "Gerador de Bio",
    description: "Gera bios curtas para perfil pessoal, criador ou loja.",
    accent: "from-cyan-500 to-indigo-600",
    inputs: [
      { name: "niche", label: "Tema", type: "text", placeholder: "frontend, ui e react", required: false },
      {
        name: "tone",
        label: "Tom",
        type: "select",
        required: true,
        options: selectOptions([
          { label: "Profissional", value: "professional" },
          { label: "Creator", value: "creator" },
          { label: "Gamer", value: "gamer" },
          { label: "Loja", value: "store" },
        ]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "6", required: true },
    ],
  },
  {
    id: "hashtagGenerator",
    slug: "gerador-de-hashtags",
    family: "generator",
    category: "geradores",
    badge: "HASH",
    name: "Gerador de Hashtags",
    description: "Monta hashtags a partir de um tema principal.",
    accent: "from-sky-500 to-blue-700",
    inputs: [
      { name: "topic", label: "Tema", type: "text", placeholder: "marketing digital", required: false },
      { name: "count", label: "Quantidade", type: "number", placeholder: "15", required: true },
    ],
  },
  {
    id: "teamNameGenerator",
    slug: "gerador-de-nomes-de-equipe",
    family: "generator",
    category: "geradores",
    badge: "TEAM",
    name: "Gerador de Nome de Equipe",
    description: "Sugere nomes para squad, time interno ou comunidade.",
    accent: "from-emerald-500 to-teal-600",
    inputs: [
      { name: "theme", label: "Tema", type: "text", placeholder: "produto", required: false },
      { name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true },
    ],
  },
  {
    id: "projectNameGenerator",
    slug: "gerador-de-nomes-de-projeto",
    family: "generator",
    category: "geradores",
    badge: "PRJ",
    name: "Gerador de Nome de Projeto",
    description: "Cria nomes curtos para apps, produtos e side projects.",
    accent: "from-violet-500 to-indigo-700",
    inputs: [
      { name: "focus", label: "Foco", type: "text", placeholder: "automacao financeira", required: false },
      { name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true },
    ],
  },
  {
    id: "emailAliasGenerator",
    slug: "gerador-de-email-alias",
    family: "generator",
    category: "geradores",
    badge: "MAIL",
    name: "Gerador de Email Alias",
    description: "Cria variacoes de alias para caixa de teste ou suporte.",
    accent: "from-cyan-500 to-sky-600",
    inputs: [
      { name: "base", label: "Base", type: "text", placeholder: "max.suporte", required: false },
      { name: "domain", label: "Dominio", type: "text", placeholder: "empresa.test", required: false },
      { name: "count", label: "Quantidade", type: "number", placeholder: "10", required: true },
    ],
  },
  {
    id: "filenameGenerator",
    slug: "gerador-de-nomes-de-arquivo",
    family: "generator",
    category: "geradores",
    badge: "FILE",
    name: "Gerador de Nome de Arquivo",
    description: "Padroniza nomes de arquivos com estilo e extensao.",
    accent: "from-slate-600 to-indigo-600",
    inputs: [
      { name: "base", label: "Base", type: "text", placeholder: "relatorio vendas abril", required: false },
      { name: "extension", label: "Extensao", type: "text", placeholder: "xlsx", required: false },
      {
        name: "style",
        label: "Estilo",
        type: "select",
        required: true,
        options: selectOptions(["kebab", "snake", "camel", "pascal"]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "8", required: true },
    ],
  },
  {
    id: "cssAnimationGenerator",
    slug: "gerador-de-animacao-css",
    family: "generator",
    category: "geradores",
    badge: "ANIM",
    name: "Gerador de Animacao CSS",
    description: "Entrega animacoes CSS prontas com keyframes e classe util.",
    accent: "from-pink-500 to-rose-600",
    inputs: [
      {
        name: "preset",
        label: "Preset",
        type: "select",
        required: true,
        options: selectOptions(["float", "pulse", "slide", "tilt"]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "3", required: true },
    ],
  },
  {
    id: "avatarSvgGenerator",
    slug: "gerador-de-avatar-svg",
    family: "generator",
    category: "geradores",
    badge: "SVG",
    name: "Gerador de Avatar SVG",
    description: "Cria placeholders SVG com iniciais e fundo colorido.",
    accent: "from-fuchsia-500 to-pink-600",
    inputs: [
      { name: "name", label: "Nome base", type: "text", placeholder: "Maria Clara", required: false },
      {
        name: "shape",
        label: "Formato",
        type: "select",
        required: true,
        options: selectOptions(["circle", "rounded", "squircle"]),
      },
      { name: "count", label: "Quantidade", type: "number", placeholder: "3", required: true },
    ],
  },
  {
    id: "wifiPayloadGenerator",
    slug: "gerador-de-payload-wifi",
    family: "generator",
    category: "geradores",
    badge: "WIFI",
    name: "Gerador de Payload Wi-Fi",
    description: "Monta strings WIFI para QR code e onboarding rapido.",
    accent: "from-teal-500 to-cyan-700",
    inputs: [
      { name: "ssid", label: "SSID", type: "text", placeholder: "Minha Rede", required: false },
      { name: "password", label: "Senha", type: "text", placeholder: "senha12345", required: false },
      {
        name: "encryption",
        label: "Seguranca",
        type: "select",
        required: true,
        options: selectOptions(["WPA", "WEP", "nopass"]),
      },
      {
        name: "hidden",
        label: "Rede oculta",
        type: "checkbox",
        defaultValue: false,
        exampleValue: false,
      },
    ],
  },
  {
    id: "commitMessageGenerator",
    slug: "gerador-de-commit",
    family: "generator",
    category: "geradores",
    badge: "GIT",
    name: "Gerador de Commit",
    description: "Sugere mensagens de commit no estilo conventional commits.",
    accent: "from-slate-700 to-emerald-700",
    inputs: [
      {
        name: "type",
        label: "Tipo",
        type: "select",
        required: true,
        options: selectOptions(["feat", "fix", "refactor", "chore", "docs", "test"]),
      },
      { name: "scope", label: "Escopo", type: "text", placeholder: "auth", required: false },
      { name: "summary", label: "Resumo", type: "text", placeholder: "adiciona login social", required: false },
    ],
  },
];

export default generatorTools;
