function selectOptions(values) {
  return values.map((value) =>
    typeof value === "string" ? { label: value, value } : value,
  );
}

const lookupTools = [
  {
    id: "cep",
    slug: "consulta-cep",
    family: "lookup",
    category: "consultas",
    badge: "CEP",
    name: "Consulta de CEP",
    description: "Busca endereco com fallback entre BrasilAPI e ViaCEP.",
    accent: "from-cyan-500 to-sky-500",
    inputs: [
      { name: "cep", label: "CEP", type: "text", placeholder: "01310-100", required: true },
    ],
  },
  {
    id: "cnpj",
    slug: "consulta-cnpj",
    family: "lookup",
    category: "consultas",
    badge: "CNPJ",
    name: "Consulta de CNPJ",
    description: "Recupera dados cadastrais da empresa em um painel unificado.",
    accent: "from-orange-400 to-rose-500",
    inputs: [
      { name: "cnpj", label: "CNPJ", type: "text", placeholder: "40512337000283", required: true },
    ],
  },
  {
    id: "ddd",
    slug: "consulta-ddd",
    family: "lookup",
    category: "consultas",
    badge: "DDD",
    name: "Consulta por DDD",
    description: "Lista estado e cidades atendidas por um DDD brasileiro.",
    accent: "from-sky-500 to-indigo-500",
    inputs: [{ name: "ddd", label: "DDD", type: "text", placeholder: "11", required: true }],
  },
  {
    id: "ncm",
    slug: "consulta-ncm",
    family: "lookup",
    category: "consultas",
    badge: "NCM",
    name: "Consulta de NCM",
    description: "Pesquisa por codigo ou descricao de classificacoes fiscais.",
    accent: "from-teal-400 to-cyan-600",
    inputs: [
      {
        name: "query",
        label: "Codigo ou descricao",
        type: "text",
        placeholder: "84713012 ou notebook",
        required: true,
      },
    ],
  },
  {
    id: "fipeMarcas",
    slug: "fipe-marcas",
    family: "lookup",
    category: "consultas",
    badge: "FIPE",
    name: "Marcas FIPE",
    description: "Lista marcas por tipo de veiculo para iniciar a consulta de preco.",
    accent: "from-amber-400 to-orange-500",
    inputs: [
      {
        name: "type",
        label: "Tipo de veiculo",
        type: "select",
        required: true,
        options: selectOptions([
          { label: "Carros", value: "carros" },
          { label: "Motos", value: "motos" },
          { label: "Caminhoes", value: "caminhoes" },
        ]),
      },
    ],
  },
  {
    id: "fipePreco",
    slug: "fipe-preco",
    family: "lookup",
    category: "consultas",
    badge: "R$",
    name: "Preco FIPE",
    description: "Busca o preco atual de um codigo FIPE especifico.",
    accent: "from-orange-500 to-red-500",
    inputs: [
      { name: "code", label: "Codigo FIPE", type: "text", placeholder: "001267-0", required: true },
    ],
  },
  {
    id: "banks",
    slug: "consulta-bancos",
    family: "lookup",
    category: "consultas",
    badge: "001",
    name: "Consulta de Bancos",
    description: "Retorna todos os bancos ou consulta um codigo bancario especifico.",
    accent: "from-violet-400 to-indigo-500",
    inputs: [
      { name: "code", label: "Codigo bancario", type: "text", placeholder: "001", required: false },
    ],
  },
  {
    id: "taxas",
    slug: "taxas-oficiais",
    family: "lookup",
    category: "consultas",
    badge: "TAXA",
    name: "Taxas Oficiais",
    description: "Consulta indicadores e taxas de juros por nome ou sigla.",
    accent: "from-emerald-400 to-teal-500",
    inputs: [
      { name: "name", label: "Nome ou sigla", type: "text", placeholder: "cdi", required: false },
    ],
  },
  {
    id: "feriados",
    slug: "feriados-nacionais",
    family: "lookup",
    category: "consultas",
    badge: "ANO",
    name: "Feriados Nacionais",
    description: "Lista os feriados nacionais do ano informado.",
    accent: "from-pink-400 to-rose-500",
    inputs: [{ name: "year", label: "Ano", type: "number", placeholder: "2026", required: true }],
  },
  {
    id: "registroBr",
    slug: "consulta-dominio",
    family: "lookup",
    category: "consultas",
    badge: "DNS",
    name: "Consulta de Dominio",
    description: "Verifica a situacao de um dominio no Registro.br.",
    accent: "from-slate-500 to-cyan-600",
    inputs: [
      { name: "domain", label: "Dominio", type: "text", placeholder: "paradevs.com.br", required: true },
    ],
  },
  {
    id: "cptecClima",
    slug: "previsao-do-tempo",
    family: "lookup",
    category: "consultas",
    badge: "CLIMA",
    name: "Previsao do Tempo",
    description: "Encontra a cidade e recupera a previsao CPTEC.",
    accent: "from-sky-400 to-blue-500",
    inputs: [{ name: "city", label: "Cidade", type: "text", placeholder: "Salvador", required: true }],
  },
  {
    id: "pixParticipantes",
    slug: "participantes-pix",
    family: "lookup",
    category: "consultas",
    badge: "PIX",
    name: "Participantes do PIX",
    description: "Lista participantes ativos do ecossistema PIX.",
    accent: "from-emerald-500 to-lime-500",
    inputs: [],
  },
  {
    id: "ipInfo",
    slug: "meu-ip",
    family: "lookup",
    category: "consultas",
    badge: "IP",
    name: "Meu IP",
    description: "Exibe IP publico, ISP, localizacao e ASN.",
    accent: "from-cyan-400 to-teal-500",
    inputs: [],
  },
  {
    id: "cepAddressSearch",
    slug: "cep-por-endereco",
    family: "lookup",
    category: "consultas",
    badge: "RUA",
    name: "CEP por Endereco",
    description: "Procura CEPs a partir de UF, cidade e logradouro.",
    accent: "from-blue-500 to-cyan-500",
    inputs: [
      { name: "uf", label: "UF", type: "text", placeholder: "BA", required: true },
      { name: "city", label: "Cidade", type: "text", placeholder: "Salvador", required: true },
      { name: "street", label: "Logradouro", type: "text", placeholder: "Avenida Sete de Setembro", required: true },
    ],
  },
  {
    id: "ipLookup",
    slug: "consulta-ip",
    family: "lookup",
    category: "consultas",
    badge: "IP+",
    name: "Consulta de IP",
    description: "Inspeciona geolocalizacao e ASN de um IP especifico.",
    accent: "from-cyan-500 to-indigo-500",
    inputs: [{ name: "ip", label: "IP", type: "text", placeholder: "8.8.8.8", required: true }],
  },
  {
    id: "reverseDns",
    slug: "reverse-dns",
    family: "lookup",
    category: "consultas",
    badge: "PTR",
    name: "Reverse DNS",
    description: "Resolve um IP para os hostnames associados.",
    accent: "from-slate-500 to-sky-600",
    inputs: [{ name: "ip", label: "IP", type: "text", placeholder: "8.8.8.8", required: true }],
  },
  ...[
    {
      id: "dnsA",
      slug: "dns-a",
      badge: "A",
      name: "DNS A",
      description: "Consulta registros A de um dominio.",
      accent: "from-sky-500 to-blue-600",
    },
    {
      id: "dnsMx",
      slug: "dns-mx",
      badge: "MX",
      name: "DNS MX",
      description: "Consulta servidores de email de um dominio.",
      accent: "from-amber-400 to-orange-500",
    },
    {
      id: "dnsNs",
      slug: "dns-ns",
      badge: "NS",
      name: "DNS NS",
      description: "Consulta nameservers publicados pelo dominio.",
      accent: "from-violet-400 to-indigo-500",
    },
    {
      id: "dnsTxt",
      slug: "dns-txt",
      badge: "TXT",
      name: "DNS TXT",
      description: "Consulta registros TXT como SPF e verificacoes.",
      accent: "from-emerald-400 to-teal-500",
    },
  ].map((tool) => ({
    ...tool,
    family: "lookup",
    category: "consultas",
    inputs: [{ name: "host", label: "Dominio", type: "text", placeholder: "google.com", required: true }],
  })),
  {
    id: "sslCertificate",
    slug: "certificado-ssl",
    family: "lookup",
    category: "consultas",
    badge: "SSL",
    name: "Certificado SSL",
    description: "Inspeciona emissor, validade e subject do certificado.",
    accent: "from-green-500 to-cyan-600",
    inputs: [
      { name: "host", label: "Dominio", type: "text", placeholder: "openai.com", required: true },
      { name: "port", label: "Porta", type: "number", placeholder: "443", required: false },
    ],
  },
  {
    id: "httpHeadersLookup",
    slug: "cabecalhos-http",
    family: "lookup",
    category: "consultas",
    badge: "HEAD",
    name: "Cabecalhos HTTP",
    description: "Busca os cabecalhos de resposta de uma URL.",
    accent: "from-cyan-500 to-blue-600",
    inputs: [{ name: "url", label: "URL", type: "text", placeholder: "https://example.com", required: true }],
  },
  {
    id: "robotsLookup",
    slug: "robots-txt",
    family: "lookup",
    category: "consultas",
    badge: "BOT",
    name: "Robots.txt",
    description: "Recupera e exibe o arquivo robots.txt de um site.",
    accent: "from-slate-600 to-slate-800",
    inputs: [{ name: "url", label: "URL base", type: "text", placeholder: "https://example.com", required: true }],
  },
  {
    id: "sitemapLookup",
    slug: "sitemap-xml",
    family: "lookup",
    category: "consultas",
    badge: "XML",
    name: "Sitemap XML",
    description: "Busca o sitemap principal e mostra o conteudo bruto.",
    accent: "from-indigo-500 to-cyan-600",
    inputs: [{ name: "url", label: "URL base", type: "text", placeholder: "https://example.com", required: true }],
  },
  {
    id: "githubProfileLookup",
    slug: "github-perfil",
    family: "lookup",
    category: "consultas",
    badge: "GH",
    name: "Perfil GitHub",
    description: "Consulta dados publicos de um usuario do GitHub.",
    accent: "from-slate-700 to-slate-900",
    inputs: [{ name: "username", label: "Usuario", type: "text", placeholder: "octocat", required: true }],
  },
  {
    id: "githubRepoLookup",
    slug: "github-repositorio",
    family: "lookup",
    category: "consultas",
    badge: "REPO",
    name: "Repositorio GitHub",
    description: "Consulta metadados publicos de um repositorio.",
    accent: "from-slate-800 to-blue-700",
    inputs: [
      { name: "owner", label: "Owner", type: "text", placeholder: "openai", required: true },
      { name: "repo", label: "Repositorio", type: "text", placeholder: "openai-node", required: true },
    ],
  },
  {
    id: "npmPackageLookup",
    slug: "npm-pacote",
    family: "lookup",
    category: "consultas",
    badge: "NPM",
    name: "Pacote NPM",
    description: "Consulta versoes, descricao e metadados de um pacote NPM.",
    accent: "from-red-500 to-orange-500",
    inputs: [{ name: "packageName", label: "Pacote", type: "text", placeholder: "react", required: true }],
  },
  {
    id: "npmDownloadsLookup",
    slug: "npm-downloads",
    family: "lookup",
    category: "consultas",
    badge: "DL",
    name: "Downloads NPM",
    description: "Consulta downloads da ultima semana de um pacote.",
    accent: "from-orange-500 to-amber-500",
    inputs: [{ name: "packageName", label: "Pacote", type: "text", placeholder: "vite", required: true }],
  },
  {
    id: "pypiPackageLookup",
    slug: "pypi-pacote",
    family: "lookup",
    category: "consultas",
    badge: "PYPI",
    name: "Pacote PyPI",
    description: "Consulta release, resumo e informacoes de um pacote Python.",
    accent: "from-yellow-400 to-blue-600",
    inputs: [{ name: "packageName", label: "Pacote", type: "text", placeholder: "requests", required: true }],
  },
  {
    id: "isbnLookup",
    slug: "consulta-isbn",
    family: "lookup",
    category: "consultas",
    badge: "ISBN",
    name: "Consulta ISBN",
    description: "Busca dados de livros a partir de um ISBN.",
    accent: "from-violet-500 to-fuchsia-500",
    inputs: [{ name: "isbn", label: "ISBN", type: "text", placeholder: "9788575228289", required: true }],
  },
  {
    id: "countryLookup",
    slug: "consulta-pais",
    family: "lookup",
    category: "consultas",
    badge: "PAIS",
    name: "Consulta de Pais",
    description: "Retorna dados gerais de um pais a partir do nome.",
    accent: "from-teal-500 to-blue-500",
    inputs: [{ name: "name", label: "Pais", type: "text", placeholder: "Brazil", required: true }],
  },
  {
    id: "ibgeStatesLookup",
    slug: "ufs-brasil",
    family: "lookup",
    category: "consultas",
    badge: "UF",
    name: "UFs do Brasil",
    description: "Lista unidades federativas e codigos oficiais do IBGE.",
    accent: "from-cyan-500 to-teal-600",
    inputs: [],
  },
  {
    id: "ibgeCitiesLookup",
    slug: "municipios-por-uf",
    family: "lookup",
    category: "consultas",
    badge: "CITY",
    name: "Municipios por UF",
    description: "Lista os municipios de uma UF usando dados do IBGE.",
    accent: "from-blue-500 to-indigo-600",
    inputs: [{ name: "uf", label: "UF", type: "text", placeholder: "SP", required: true }],
  },
];

export default lookupTools;
