function selectOptions(values) {
  return values.map((value) =>
    typeof value === "string" ? { label: value, value } : value,
  );
}

const testerTools = [
  {
    id: "httpTester",
    slug: "teste-http",
    family: "tester",
    category: "api-teste",
    badge: "HTTP",
    name: "Teste HTTP",
    description: "Dispara requisicoes com metodo, cabecalhos e corpo personalizados.",
    accent: "from-cyan-500 to-blue-600",
    inputs: [
      { name: "url", label: "URL", type: "text", placeholder: "https://jsonplaceholder.typicode.com/posts/1", required: true },
      { name: "method", label: "Metodo", type: "select", required: true, options: selectOptions(["GET", "POST", "PUT", "PATCH", "DELETE"]) },
      { name: "headers", label: "Cabecalhos JSON", type: "textarea", placeholder: '{\n  "Content-Type": "application/json"\n}' },
      { name: "body", label: "Body", type: "textarea", placeholder: '{\n  "title": "novo item"\n}' },
    ],
  },
  {
    id: "regexTester",
    slug: "teste-regex",
    family: "tester",
    category: "api-teste",
    badge: "REGEX",
    name: "Teste de Regex",
    description: "Executa expressoes regulares com flags e destaca matches.",
    accent: "from-orange-400 to-amber-500",
    inputs: [
      { name: "pattern", label: "Padrao", type: "text", placeholder: "\\b[A-Z]{2}\\d{4}\\b", required: true },
      { name: "flags", label: "Flags", type: "text", placeholder: "gi", required: false },
      { name: "text", label: "Texto de teste", type: "textarea", placeholder: "AB1234\nCD4321", required: true },
    ],
  },
  {
    id: "jwtDecoder",
    slug: "decoder-jwt",
    family: "tester",
    category: "api-teste",
    badge: "JWT",
    name: "Decoder JWT",
    description: "Ler header e payload de tokens sem depender de bibliotecas externas.",
    accent: "from-violet-500 to-indigo-600",
    inputs: [{ name: "token", label: "JWT", type: "textarea", placeholder: "eyJhbGciOi...", required: true }],
  },
  {
    id: "hashGenerator",
    slug: "hash-sha256",
    family: "tester",
    category: "api-teste",
    badge: "SHA",
    name: "Hash SHA-256",
    description: "Gera hash SHA-256 no navegador para textos e payloads.",
    accent: "from-slate-600 to-slate-800",
    inputs: [{ name: "text", label: "Texto", type: "textarea", placeholder: "Digite o conteudo aqui", required: true }],
  },
  {
    id: "jsonValidator",
    slug: "validador-json",
    family: "tester",
    category: "api-teste",
    badge: "JSON",
    name: "Validador JSON",
    description: "Valida um JSON e mostra tipo, chaves e tamanho.",
    accent: "from-cyan-500 to-sky-600",
    inputs: [{ name: "text", label: "JSON", type: "textarea", placeholder: '{\n  "ok": true\n}', required: true }],
  },
  {
    id: "jsonMinifier",
    slug: "minificador-json",
    family: "tester",
    category: "api-teste",
    badge: "MIN",
    name: "Minificador JSON",
    description: "Compacta JSON valido em uma unica linha.",
    accent: "from-blue-500 to-indigo-500",
    inputs: [{ name: "text", label: "JSON", type: "textarea", placeholder: '{\n  "ok": true\n}', required: true }],
  },
  {
    id: "urlInspector",
    slug: "inspector-de-url",
    family: "tester",
    category: "api-teste",
    badge: "URL",
    name: "Inspector de URL",
    description: "Quebra uma URL em protocolo, host, path e query params.",
    accent: "from-teal-500 to-cyan-600",
    inputs: [{ name: "url", label: "URL", type: "text", placeholder: "https://example.com/path?a=1&b=2", required: true }],
  },
  {
    id: "queryStringParser",
    slug: "parser-de-query-string",
    family: "tester",
    category: "api-teste",
    badge: "QS",
    name: "Parser de Query String",
    description: "Converte query string em objeto legivel.",
    accent: "from-emerald-500 to-teal-500",
    inputs: [{ name: "text", label: "Query", type: "textarea", placeholder: "a=1&b=2&b=3", required: true }],
  },
  {
    id: "uuidValidator",
    slug: "validador-uuid",
    family: "tester",
    category: "api-teste",
    badge: "UUID",
    name: "Validador UUID",
    description: "Confere se o valor informado e um UUID valido.",
    accent: "from-violet-500 to-indigo-600",
    inputs: [{ name: "text", label: "UUID", type: "text", placeholder: "550e8400-e29b-41d4-a716-446655440000", required: true }],
  },
  {
    id: "cpfValidator",
    slug: "validador-cpf",
    family: "tester",
    category: "api-teste",
    badge: "CPF",
    name: "Validador CPF",
    description: "Valida o digito verificador de um CPF.",
    accent: "from-emerald-500 to-lime-500",
    inputs: [{ name: "text", label: "CPF", type: "text", placeholder: "39053344705", required: true }],
  },
  {
    id: "cnpjValidator",
    slug: "validador-cnpj",
    family: "tester",
    category: "api-teste",
    badge: "CNPJ",
    name: "Validador CNPJ",
    description: "Valida o digito verificador de um CNPJ.",
    accent: "from-orange-500 to-rose-500",
    inputs: [{ name: "text", label: "CNPJ", type: "text", placeholder: "27865757000102", required: true }],
  },
  {
    id: "emailValidator",
    slug: "validador-email",
    family: "tester",
    category: "api-teste",
    badge: "MAIL",
    name: "Validador de Email",
    description: "Checa formato basico de um email.",
    accent: "from-pink-500 to-fuchsia-600",
    inputs: [{ name: "text", label: "Email", type: "text", placeholder: "dev@empresa.com", required: true }],
  },
  {
    id: "passwordStrength",
    slug: "forca-de-senha",
    family: "tester",
    category: "api-teste",
    badge: "PWD",
    name: "Forca de Senha",
    description: "Avalia tamanho, variedade e previsibilidade da senha.",
    accent: "from-slate-600 to-indigo-700",
    inputs: [{ name: "text", label: "Senha", type: "textarea", placeholder: "MinhaSenha@123", required: true }],
  },
  {
    id: "hmacSha256",
    slug: "hmac-sha256",
    family: "tester",
    category: "api-teste",
    badge: "HMAC",
    name: "HMAC SHA-256",
    description: "Assina um texto com segredo usando HMAC SHA-256.",
    accent: "from-cyan-600 to-blue-700",
    inputs: [
      { name: "text", label: "Mensagem", type: "textarea", placeholder: "payload", required: true },
      { name: "secret", label: "Segredo", type: "text", placeholder: "minha-chave", required: true },
    ],
  },
  {
    id: "sha1HashTester",
    slug: "hash-sha1",
    family: "tester",
    category: "api-teste",
    badge: "SHA1",
    name: "Hash SHA-1",
    description: "Calcula SHA-1 para compatibilidade legada.",
    accent: "from-amber-500 to-orange-600",
    inputs: [{ name: "text", label: "Texto", type: "textarea", placeholder: "conteudo", required: true }],
  },
  {
    id: "sha512HashTester",
    slug: "hash-sha512",
    family: "tester",
    category: "api-teste",
    badge: "SHA512",
    name: "Hash SHA-512",
    description: "Calcula hash SHA-512 para comparacao e integridade.",
    accent: "from-slate-700 to-black",
    inputs: [{ name: "text", label: "Texto", type: "textarea", placeholder: "conteudo", required: true }],
  },
  {
    id: "basicAuthInspector",
    slug: "basic-auth",
    family: "tester",
    category: "api-teste",
    badge: "AUTH",
    name: "Basic Auth",
    description: "Codifica ou decodifica credenciais Basic Auth.",
    accent: "from-blue-500 to-cyan-700",
    inputs: [
      {
        name: "mode",
        label: "Modo",
        type: "select",
        required: true,
        options: selectOptions([
          { label: "Codificar", value: "encode" },
          { label: "Decodificar", value: "decode" },
        ]),
      },
      { name: "text", label: "Conteudo", type: "textarea", placeholder: "usuario:senha ou Basic ZGV2OnNlY3JldA==", required: true },
    ],
  },
  {
    id: "unixTimestampConverter",
    slug: "conversor-de-timestamp",
    family: "tester",
    category: "api-teste",
    badge: "TS",
    name: "Conversor de Timestamp",
    description: "Converte unix timestamp em datas ou datas em timestamp.",
    accent: "from-emerald-500 to-cyan-600",
    inputs: [{ name: "text", label: "Valor", type: "text", placeholder: "1712781600 ou 2026-04-10T12:00:00Z", required: true }],
  },
  {
    id: "semverComparator",
    slug: "comparador-semver",
    family: "tester",
    category: "api-teste",
    badge: "SEMVER",
    name: "Comparador Semver",
    description: "Compara duas versoes seguindo major, minor e patch.",
    accent: "from-violet-500 to-sky-600",
    inputs: [
      { name: "versionA", label: "Versao A", type: "text", placeholder: "1.4.0", required: true },
      { name: "versionB", label: "Versao B", type: "text", placeholder: "1.3.9", required: true },
    ],
  },
  {
    id: "mimeTypeLookup",
    slug: "consulta-mime-type",
    family: "tester",
    category: "api-teste",
    badge: "MIME",
    name: "Consulta MIME Type",
    description: "Busca extensao, mime type e categoria mais comum.",
    accent: "from-teal-500 to-indigo-500",
    inputs: [{ name: "text", label: "Extensao ou MIME", type: "text", placeholder: ".json ou application/json", required: true }],
  },
  {
    id: "regexReplaceTester",
    slug: "regex-replace",
    family: "tester",
    category: "api-teste",
    badge: "REPL",
    name: "Regex Replace",
    description: "Testa substituicoes com regex, flags e texto alvo.",
    accent: "from-orange-500 to-red-500",
    inputs: [
      { name: "pattern", label: "Padrao", type: "text", placeholder: "\\s+", required: true },
      { name: "flags", label: "Flags", type: "text", placeholder: "g", required: false },
      { name: "replacement", label: "Substituicao", type: "text", placeholder: "-", required: true },
      { name: "text", label: "Texto", type: "textarea", placeholder: "valor   com   espacos", required: true },
    ],
  },
  {
    id: "xmlValidator",
    slug: "validador-xml",
    family: "tester",
    category: "api-teste",
    badge: "XML",
    name: "Validador XML",
    description: "Verifica se o XML esta bem formado.",
    accent: "from-sky-500 to-indigo-600",
    inputs: [{ name: "text", label: "XML", type: "textarea", placeholder: "<root><item>ok</item></root>", required: true }],
  },
  {
    id: "xmlFormatter",
    slug: "formatador-xml",
    family: "tester",
    category: "api-teste",
    badge: "FMT",
    name: "Formatador XML",
    description: "Organiza XML com indentacao legivel.",
    accent: "from-cyan-500 to-teal-600",
    inputs: [{ name: "text", label: "XML", type: "textarea", placeholder: "<root><item>ok</item></root>", required: true }],
  },
  {
    id: "jwtExpirationInspector",
    slug: "jwt-expiracao",
    family: "tester",
    category: "api-teste",
    badge: "EXP",
    name: "JWT Expiracao",
    description: "Analisa exp, iat e janela de validade do token.",
    accent: "from-indigo-500 to-violet-600",
    inputs: [{ name: "token", label: "JWT", type: "textarea", placeholder: "eyJhbGciOi...", required: true }],
  },
];

export default testerTools;
