const baseTools = [
  {
    id: "jsonFormat",
    slug: "formatador-json",
    badge: "{ }",
    name: "Formatador JSON",
    description: "Valida, organiza e embeleza JSON bruto.",
    accent: "from-cyan-500 to-blue-500",
  },
  {
    id: "base64",
    slug: "base64",
    badge: "64",
    name: "Base64",
    description: "Codifica e decodifica textos com suporte a unicode.",
    accent: "from-fuchsia-400 to-violet-500",
  },
  {
    id: "caseConverter",
    slug: "conversor-de-cases",
    badge: "Aa",
    name: "Conversor de Cases",
    description: "Gera versoes em camel, pascal, snake e kebab.",
    accent: "from-sky-500 to-indigo-500",
  },
  {
    id: "urlTools",
    slug: "url-encode-decode",
    badge: "%",
    name: "URL Encode e Decode",
    description: "Escapa, restaura e inspeciona parametros de URL.",
    accent: "from-amber-400 to-orange-500",
  },
  {
    id: "textStats",
    slug: "estatisticas-de-texto",
    badge: "TXT",
    name: "Estatisticas de Texto",
    description: "Conta caracteres, palavras, linhas e remove duplicidades.",
    accent: "from-teal-500 to-emerald-500",
  },
  {
    id: "slugify",
    slug: "gerador-de-slug",
    badge: "SEO",
    name: "Gerador de Slug",
    description: "Converte titulos em slugs limpos para URL.",
    accent: "from-slate-500 to-slate-700",
  },
  {
    id: "removeAccents",
    slug: "remover-acentos",
    badge: "LAT",
    name: "Remover Acentos",
    description: "Normaliza caracteres acentuados para ASCII simples.",
    accent: "from-cyan-500 to-sky-600",
  },
  {
    id: "reverseText",
    slug: "inverter-texto",
    badge: "REV",
    name: "Inverter Texto",
    description: "Inverte completamente a ordem dos caracteres.",
    accent: "from-indigo-500 to-violet-600",
  },
  {
    id: "titleCaseText",
    slug: "title-case",
    badge: "CASE",
    name: "Title Case",
    description: "Capitaliza cada palavra do texto informado.",
    accent: "from-orange-500 to-amber-500",
  },
  {
    id: "trimLines",
    slug: "trim-de-linhas",
    badge: "TRIM",
    name: "Trim de Linhas",
    description: "Remove espacos extras nas extremidades de cada linha.",
    accent: "from-teal-500 to-cyan-600",
  },
  {
    id: "removeBlankLines",
    slug: "remover-linhas-vazias",
    badge: "CLEAN",
    name: "Remover Linhas Vazias",
    description: "Filtra linhas sem conteudo para deixar o texto enxuto.",
    accent: "from-emerald-500 to-teal-500",
  },
  {
    id: "sortLines",
    slug: "ordenar-linhas",
    badge: "AZ",
    name: "Ordenar Linhas",
    description: "Ordena linhas em ordem alfabetica.",
    accent: "from-sky-500 to-blue-600",
  },
  {
    id: "uniqueLinesTool",
    slug: "linhas-unicas",
    badge: "UNIQ",
    name: "Linhas Unicas",
    description: "Remove linhas duplicadas mantendo a primeira ocorrencia.",
    accent: "from-violet-500 to-indigo-500",
  },
  {
    id: "lineNumbering",
    slug: "numerar-linhas",
    badge: "#",
    name: "Numerar Linhas",
    description: "Adiciona indice sequencial a cada linha do texto.",
    accent: "from-slate-600 to-slate-800",
  },
  {
    id: "extractEmails",
    slug: "extrator-de-emails",
    badge: "@",
    name: "Extrator de Emails",
    description: "Localiza e lista emails presentes em qualquer texto.",
    accent: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "extractUrls",
    slug: "extrator-de-urls",
    badge: "URL",
    name: "Extrator de URLs",
    description: "Extrai links HTTP e HTTPS encontrados no conteudo.",
    accent: "from-cyan-500 to-teal-500",
  },
  {
    id: "extractNumbers",
    slug: "extrator-de-numeros",
    badge: "123",
    name: "Extrator de Numeros",
    description: "Captura numeros inteiros e decimais no texto.",
    accent: "from-amber-500 to-orange-500",
  },
  {
    id: "wordFrequency",
    slug: "frequencia-de-palavras",
    badge: "TOP",
    name: "Frequencia de Palavras",
    description: "Mostra as palavras mais frequentes no texto.",
    accent: "from-blue-500 to-indigo-600",
  },
  {
    id: "readingTime",
    slug: "tempo-de-leitura",
    badge: "READ",
    name: "Tempo de Leitura",
    description: "Estima o tempo de leitura com base na contagem de palavras.",
    accent: "from-emerald-500 to-lime-500",
  },
  {
    id: "htmlEntitiesEncode",
    slug: "html-entities-encode",
    badge: "HTML",
    name: "HTML Entities Encode",
    description: "Escapa caracteres especiais para entidades HTML.",
    accent: "from-orange-400 to-red-500",
  },
  {
    id: "htmlEntitiesDecode",
    slug: "html-entities-decode",
    badge: "DECODE",
    name: "HTML Entities Decode",
    description: "Converte entidades HTML para caracteres normais.",
    accent: "from-red-400 to-pink-500",
  },
  {
    id: "jsonEscape",
    slug: "escape-json-string",
    badge: "ESC",
    name: "Escape JSON String",
    description: "Escapa aspas, barras e quebras para string JSON segura.",
    accent: "from-indigo-500 to-blue-600",
  },
  {
    id: "csvToJson",
    slug: "csv-para-json",
    badge: "CSV",
    name: "CSV para JSON",
    description: "Transforma tabelas CSV simples em JSON.",
    accent: "from-emerald-500 to-cyan-500",
  },
  {
    id: "jsonToCsv",
    slug: "json-para-csv",
    badge: "JSON",
    name: "JSON para CSV",
    description: "Converte arrays JSON em tabela CSV.",
    accent: "from-cyan-500 to-blue-500",
  },
  {
    id: "textToBulletList",
    slug: "texto-para-lista",
    badge: "LIST",
    name: "Texto para Lista",
    description: "Transforma linhas em lista markdown com bullets.",
    accent: "from-violet-500 to-fuchsia-600",
  },
  {
    id: "removeDuplicateWords",
    slug: "remover-palavras-duplicadas",
    badge: "WORDS",
    name: "Remover Palavras Duplicadas",
    description: "Remove repeticoes de palavras preservando a primeira aparicao.",
    accent: "from-slate-500 to-cyan-600",
  },
];

const textTools = baseTools.map((tool) => ({
  ...tool,
  family: "text",
  category: "texto",
}));

export default textTools;
